### ISSUE TITLE
MISP live dashboard 

### ISSUE THREAD

**Issue by dmolina213** [MISP/misp-dashboard#117]
I noticed that access to the dashboard via the browser is via localhost. So i am assuming it is being accessed via a browser local to the MISP server.  I want to access the dashboard remotely via my local browser. What are the changes necessary to enable that?

**Comment by mokaddem** [comment]
If you using the CIRCL training VM, the dashboard is served by the same apache as MISP.

**Comment by dmolina213** [comment]
I am not using the CIRCL training VM. we have a dockerized install of MISP. how do I access the dashboard from a remote browser. From the instructions they are accessing the dashboard using localhost so it’s either it’s accessed directly on the book or an ssh connection must first be established prior to browser

**Comment by dmolina213** [comment]
when i try to run ./start_all. it is giving me the error that pycountry is not found. I did a pip install pycountry and i get more errors. Any idease?
