### ISSUE TITLE
Issue with live dashboard

### ISSUE THREAD

**Issue by dmolina213** [MISP/misp-dashboard#120]
Work environment
 |Type of issue | support
 |OS version (server) | RedHat
 |MISP| Implemented on docker/ubuntu
 |OS version (client) | windows 7
 |PHP version | 7.2.10
 |MISP version / git hash | v2.4.107 ()

I have a dockerized instance of MISP running on RHEL. I am trying to set up live dashboards using instructions from GIThub and https://www.vanimpe.eu/2017/10/31/misp-dashboard-real-time-visualization-misp-events/?unapproved=119326&moderation-hash=42c28b90ab7feb92001c20f2eebe64b6#comment-119326

Although I had some error /warning messages when running ./server.py see MISP/misp-dashboard#119 . I am able to bring up the dashboard but no data appears. I even tried to publish an event to zmq
image
![image](https://user-images.githubusercontent.com/42444130/62209944-90423080-b360-11e9-90c2-dd638568d961.png)

Can anyone help me with this issue?

**Comment by mokaddem** [comment]
It seems that your server is not providing all files needed by the user interface to work. Could you check in your browser logs as well as on your installation folder if you can spot something that might cause your issue?

**Comment by dmolina213** [comment]
what am i looking for in the installation folder? I cloned everything needed that is in the github.  I was side tracked a bit but I will look into it. In all, I dont know what to really look for.  Also I am running MISP in docker. would that need additional configurations ?

**Comment by mokaddem** [comment]
As long as the Dashboard has access to the MISP ZMQ, it should not be a problem to run it in a docker container.
What does the browser console and network tabs says when you browse the trending page? It seems broken according to the screenshot.

**Comment by dmolina213** [comment]
Right now, it says service unavailable. I stopped looking at it for 2 weeks. I may have to restart services again or do some troubleshooting. I this case do you know what and where should i start to look?  
Anyways, back to answering your latest reply. The trendings page appears broken and i followed the steps listed in github that i know of. Are there others steps which I may have missed.  

i followed this : Maybe we can start here to figure what is wrong

1. Be sure to have a running redis server: e.g.
◦ redis-server -p 6250    <---- this is what I am seeing redis       16  0.6  1.5 208240 149256 ?       Sl   Aug06  61:47 /usr/bin/redis-server 0.0.0.0:6379.  what is the -p option for. I am not familiar with Redis
2. Update your configuration in config.cfg <- what do i need to update here
3. Activate your virtualenv: 
◦ . ./DASHENV/bin/activate
4. Listen to the MISP feed by starting the zmq subscriber:
◦ ./zmq subscriber.py
5. Start the dispatcher to process received messages:
◦ ./zmq dispatcher.py
6. Start the Flask server:
◦ ./server.py
7. Access the interface at http://localhost:8001/

**Comment by dmolina213** [comment]
Let me know if the above makes sense and is the correct responses from MISP before i start venturing out and doing the rest of the commands.

**Comment by dmolina213** [comment]
I tried running start_all.sh. I am getting an error when it tries to run ./server.py
The scripts call to import pycountry.
Traceback (most recent call last):
  File "./server.py", line 12, in <module>
    import pycountry
ModuleNotFoundError: No module named 'pycountry'

**Comment by Kortho** [comment]
Had the same problem, here is a fix: https://github.com/MISP/misp-dashboard/pull/114
Its not optimal, but should work

**Comment by dmolina213** [comment]
What do you mean by :

I'm not sure this is the correct way to do it.
IMHO, you should be in an virtualenv before starting start_all.sh
 
 @Kortho
Kortho 
commented about 2 months ago
sort of agree, but if so, it should be "python3 ${DIR}/server.py &"
And all the stuff with venv could just be removed. By doing it this way, the code works, and the user does not have to worry about it at all (make it easier to be more secure for the user)

**Comment by mokaddem** [comment]
The ``start_all`` script has been written by different people and I guess everyone does not use the "standard way" if there is one.

For your issue, just make sure you are in a virtualenv before starting the script.
```
. ./DASHENV/bin/activate
```
