### ISSUE TITLE
Internal Server Error after update

### ISSUE THREAD

**Issue by b00lpy** [MISP/misp-dashboard#122]
I updated misp-dashboard to v1.3.

Steps to reproduce:
Stop all python3 zmq processes.
Run `git pull`
Run `install_dependencies.sh`
Run `start_all.sh`

And now i got this.
![image](https://user-images.githubusercontent.com/50588190/64106199-febb4980-cd77-11e9-907b-af22fcffe85d.png)

**Comment by mokaddem** [comment]
Hello,
Please try the followings in order, it might solve your issue at some point:
- Restart apache2 ``service apache2 restart``
- Your ``config/config.cfg`` might have been modified during the update process. Make sure that the maxmind geo DB path is correct (in case of doubt, set it as an absolute path)
- Make sure all your python scripts are correctly running inside their screen session. Be default it is launched as the ``zmqs`` user
    - ``sudo su zmqs``
    - ``screen -ls``
    - ``screen -r [pid]``
    - navigate in the window and check if everything is ok
- reboot ;)

if neither of these steps succeeded to make the dashboard work, could you please send us the tail of log files right after you try to connect to the web interface?
They are locate in:
- ``misp-dashboard/logs``
- ``/var/logs/apache2/misp-dashboard.local_error.log``

**Comment by b00lpy** [comment]
Actually just performing the 2nd step worked.

> Your config/config.cfg might have been modified during the update process. Make sure that the maxmind geo DB path is correct (in case of doubt, set it as an absolute path)

When I edited `config/config.cfg`  into absolute path and saved, the dashboard immediately started working again. Hope that's normal :)  

Now I've got my dashboard back and updated, thanks you!

**Comment by mokaddem** [comment]
You're welcome, thanks for the feedback!
