### ISSUE TITLE
MISP SSL errors fixed but MISP-DASHBOARD doesn't work now

### ISSUE THREAD

**Issue by mathurin68** [MISP/misp-dashboard#124]
I added a trusted SSL certificate to the MISP instance and that fixed those errors BUT now the misp dashboard doesn't work...
"
An error occurred during a connection to misp.doi.net:8001. SSL received a record that exceeded the maximum permissible length. Error code: SSL_ERROR_RX_RECORD_TOO_LONG

    The page you are trying to view cannot be shown because the authenticity of the received data could not be verified.
    Please contact the website owners to inform them of this problem.
"
Is there something I need to change in - 
/etc/apache2/sites-enabled/misp-dashboard.conf

Thank you!!

**Comment by mathurin68** [comment]
Just copy the SSL cert paths to 
/etc/apache2/sites-enabled/misp-dashboard.conf

**Comment by mokaddem** [comment]
Thanks for getting back to us!
