### ISSUE TITLE
Can anyone help ??? how to resolve the below error ???

### ISSUE THREAD

**Issue by manikandanb975121** [MISP/misp-dashboard#125]
File "zmq_subscriber.py", line 76, in <module>
    main(args.zmqname, args.zmqurl)
  File "zmq_subscriber.py", line 54, in main
    socket.connect(zmqurl)
  File "zmq\backend\cython\socket.pyx", line 583, in zmq.backend.cython.socket.Socket.connect
  File "zmq\backend\cython\checkrc.pxd", line 25, in zmq.backend.cython.checkrc._check_rc
zmq.error.ZMQError: Protocol not supported

**Comment by mokaddem** [comment]
Hi,
Which OS are you using?
Could you also paste the output when you run ``pip freeze list`` inside your virutalenv?

**Comment by manikandanb975121** [comment]
Now i'm currently using Windows 10 operating system

**Comment by mokaddem** [comment]
Are you using the Window's Linux subsystem? Or a native Window's python installation?

**Comment by manikandanb975121** [comment]
I'm using native  Window's python installation only !

**Comment by mokaddem** [comment]
Btw, this issue may be relevant for you
https://github.com/zeromq/libzmq/issues/3691
