### ISSUE TITLE
MISP Dashboard in Ubuntu 16

### ISSUE THREAD

**Issue by darthsyaz** [MISP/misp-dashboard#131]
Hi im running a server with Misp 2.4.117 (currently latest version).

However im struggling in deploying Misp Dashboard as its my 20th attempt. :(
Might be coz im too noob
 
Removed these 3:
#       eviction-timeout=0
#       response-buffer-size=0
#       server-metrics=Off

 However i still have error as below. 
![image](https://user-images.githubusercontent.com/11624855/66808696-598eb600-ef5e-11e9-9f09-00d96206c87b.png)

Currently reverted to previous snapshot before dashboard deployment.
Not planning to move to ubuntu 18 or 19 yet as im gonna hold it until ubuntu 20 :D 

Really appreciate your kind assistance :)

**Comment by SteveClement** [comment]
Sorry for the super late answer.
We are not supporting 16.04 anymore (and were also not at the date you asked your initial question)
Sorry. But, Ubuntu 20.04 is around the corner. (April)
https://ubuntu.com/about/release-cycle
