### ISSUE TITLE
Too many redirects. This can be due to your brower not accepting cookies or the misp-dashboard website is badly configured

### ISSUE THREAD

**Issue by cudeso** [MISP/misp-dashboard#137]
Running dashboard on a hosts which was able to run the previous versions of the dashboard. Setting authentication to False. Always getting "Too many redirects. This can be due to your brower not accepting cookies or the misp-dashboard website is badly configured".

No errors in Flask, despite Debug is enabled.

**Comment by mokaddem** [comment]
Hello,
I suspect that your dashboard is not properly configured to use SSL. For the default configuration, cookie cannot be saved on non-secure website.
If my suspicion is correct, you have two choices:
1. Fix your SSL configuration for the misp-dashboard server
2. Alternatively, you can specify to still save cookies on unsecured connections in ``config.cfg``. Set ``session_cookie_secure`` to ``false``
```
[Auth]
session_cookie_secure = False
```

**Comment by cudeso** [comment]
Indeed, setting `session_cookie_secure = False` was one way of fixing it.

I fixed the Flask server (via server.py) config also to support SSL via self-signed certificate. Requires a dependency (pyOpenSSL) and `app.run(ssl_context='adhoc', host=server_host,`.

**Comment by mokaddem** [comment]
Hey, that seems great!
Could you submit a PR? :)
