### ISSUE TITLE
clean.py got error

### ISSUE THREAD

**Issue by darthsyaz** [MISP/misp-dashboard#138]
Hey there. 
I got another instance with running dashboard however i got error in executing clean.py to clear the dashboard.
Kindlys assist me :)

![image](https://user-images.githubusercontent.com/11624855/68737247-d7a5b180-061d-11ea-9bc9-11ac8d5548a6.png)

**Comment by mokaddem** [comment]
By any chance, could it be that you are not in a virtual python environment?
```
. ./DASHENV/bin/activate
```
Before starting the script

**Comment by darthsyaz** [comment]
Thanks for your reply tho but I found another error :(

![image](https://user-images.githubusercontent.com/11624855/68910023-47857a80-078b-11ea-91c3-6d0ea2cc0c37.png)
