### ISSUE TITLE
MaxMind file download issue

### ISSUE THREAD

**Issue by JanKoDFNCERT** [MISP/misp-dashboard#146]
Hi, I came across an issue pertaining to the download of the MaxMind database file. The database is named Geolite2-City.tar.gz after download. However, the file containing the sha256 hash (Geolite2-City.tar.gz.sha256 assumes a different file named Geolite2-City_<current date>.tar.gz

This leads to a failure checking the validity of the hash resulting in an infinite loop downloading the database. 
Cheers, Jan

**Comment by JanKoDFNCERT** [comment]
ups, github deleted some characters. The name expected in the .sha256 file is Geolite2-City_CURRENT_DATE.tar.gz

**Comment by SteveClement** [comment]
thanks for the report, fixing.

**Comment by SteveClement** [comment]
thanks again, it actually was already fixed, I now added also a check if the Key is wrong.
