### ISSUE TITLE
No  ZMQ Green Icon on MISP Dashboard and Run diagnostic.py server listening is red

### ISSUE THREAD

**Issue by yixiangbo** [MISP/misp-dashboard#152]
![image](https://user-images.githubusercontent.com/69097109/109465268-c6ec9b00-7a1c-11eb-94ed-71da96da70d2.png)
![image](https://user-images.githubusercontent.com/69097109/109465297-cf44d600-7a1c-11eb-8a4a-fd45d8995447.png)
server listening is error,and i didn't get the correct web of misp-dashboard

**Comment by mokaddem** [comment]
It seems you have issues to start the subscribers and dispatchers. Could you manually check if they are running and if yes, connect to their screen session to check if anything weird popped up?
