### ISSUE TITLE
NOT starting flask server

### ISSUE THREAD

**Issue by yixiangbo** [MISP/misp-dashboard#153]
![image](https://user-images.githubusercontent.com/69097109/109630867-413f1d00-7afa-11eb-89e4-2cf94a962108.png)
misp-dashboard run error , but ZMQ is running normally

**Comment by mokaddem** [comment]
It seems you have a service already running on port 8001, thus preventing the misp-dashboard server to start. 
Please, make sure the port is free before starting the dashboard or alternatively, you can change the port in the configuration file
