### ISSUE TITLE
Too many redirects cause inability to display

### ISSUE THREAD

**Issue by f47sh33p** [MISP/misp-dashboard#154]
I set up the misp-dashboard as per the manual.
I installed MISP and misp-dashboard on the same server.
Therefore, I did not change the config.conf.

When I started the program and accessed it, it did not display correctly.
I tried to run it with curl and found that many redirects occurred.
The result was as follows.

![image](https://user-images.githubusercontent.com/35436457/111487457-b7d74e00-877b-11eb-940f-948c6849c107.png)

What settings should I make to resolve this?

**Comment by f47sh33p** [comment]
There seems to be a problem with the login process.
After commenting out all @login_required, the dashboard was displayed successfully.
![image](https://user-images.githubusercontent.com/35436457/111904651-4e14b800-8a8b-11eb-991c-5c5932e5127e.png)

**Comment by mokaddem** [comment]
Hello,
[This tool](https://github.com/MISP/misp-dashboard/blob/master/diagnostic.py) can be useful to diagnose the issue.
My guess is you haven't properly configured `config.conf` and are trying to use secure cookie with SSL disabled or badly configured.
Please review the setting and let me know if it solved your issue.
Thanks!

**Comment by f47sh33p** [comment]
Hello
Thanks for the advice.
I modified the config.cfg and it worked!

```
$ diff config/config.cfg.org config/config.cfg
16c16
< session_cookie_secure = True
---
> session_cookie_secure = False
```

Thanks a lot!

**Comment by f47sh33p** [comment]
Hello
Thanks for the advice.
I modified the config.cfg and it worked!

```
$ diff config/config.cfg.org config/config.cfg
16c16
< session_cookie_secure = True
---
> session_cookie_secure = False
```

Many thanks!
