### ISSUE TITLE
Unable to connect to the MISP Dashboard, zmq_Dispatcher crashes after publishing events

### ISSUE THREAD

**Issue by EonCyr** [MISP/misp-dashboard#162]
The issue that I am currently facing is that I am unable to connect to the MISP Dashboard "http://127.0.0.1:8001". When I execute the ./diagnostics.py, it would be stuck on "Trying to connect to http://127.0.0.1:8001/_get_log_head" command line and doesn't proceed any further.

![image](https://user-images.githubusercontent.com/52245421/147899112-68433917-a370-406a-bb2b-777700cc89ed.png)

I followed the steps from https://github.com/MISP/misp-dashboard/blob/main/README.md till the ./install_dependencies.sh 
From here on, I entered the following commands:

sudo apt-get install python3-flask python3-redis -y
sudo pip install halo

redis-server --port 6250 --daemonize yes
ps aux | grep redis-server

. ./DASHENV/bin/activate
./zmq_subscriber.py &
./zmq_dispatcher.py &
./server.py &

./diagnostic.py

**Comment by EonCyr** [comment]
Currently I am having a different error after trying to debug it manually. 
![image](https://user-images.githubusercontent.com/52245421/147902623-1acc9132-1c27-4fc2-a260-9d8dcb034a7f.png)
This occurs when I attempt to push an event to the MISP dashboard, not really sure what is causing the issue. The zmq_dispatcher.py automatically crashes whenever I attempt to publish an event to the dashboard.

**Comment by whoisroot** [comment]
The error is what I was getting before fixing the redis `GEOADD` command.

Since my PR has been merged, please pull the latest version from git and try again.

**Comment by EonCyr** [comment]
Thank you, this issue has been fixed by pulling the update.
