### ISSUE TITLE
idea: a timeline based visualisation for all attributes referenced by time.

### ISSUE THREAD

**Issue by adulau** [MISP/misp-dashboard#17]
idea: a timeline based visualisation for all attributes referenced by time.

**Comment by mokaddem** [comment]
Hi,
I did it for ``events``, ``tags`` and ``attribute->category``.
Concerning attributes, did you mean:
 - ``attribute->category``
 - ``attribute->type``
 - ``attribute->value`` (To much data to show?)
 - all of them?

Thanks!

**Comment by adulau** [comment]
`attribute->value` makes sense.

**Comment by mokaddem** [comment]
Following a discussion, the timeline will not include ``attribute->value`` but can still be added if needed.
Implented in #29
