### ISSUE TITLE
Prevent the purging of the data from the live dashboard

### ISSUE THREAD

**Issue by iglocska** [MISP/misp-dashboard#28]
Switching to a different view seems to purge the previous data from the live dashboard view. Could we make it persistent for the duration of the session / some other mechanism?

**Comment by adulau** [comment]
Indeed. The other tab are indeed persistent but the first page. 

@mokaddem will have a look to keep the first page persistent using a session cookies.

**Comment by adulau** [comment]
Fixed in bb2ea839f34eb03fc59625f7041473e801cebcff
