### ISSUE TITLE
ZMQ Dispatcher Error: JSONDecodeError("Expecting value")

### ISSUE THREAD

**Issue by faustus25** [MISP/misp-dashboard#71]
Had the same issue with the zmq_subscriber script now the zmq_dispatcher.py one has this issue:

````
echo 'source /usr/local/src/misp-dashboard/DASHENV/bin/activate; /usr/bin/python3 /usr/local/src/misp-dashboard/zmq_dispatcher.py' | /bin/bash

Traceback (most recent call last):
  File "/usr/local/src/misp-dashboard/zmq_dispatcher.py", line 299, in <module>
    main(args.sleeptime)
  File "/usr/local/src/misp-dashboard/zmq_dispatcher.py", line 274, in main
    process_log(zmqName, content)
  File "/usr/local/src/misp-dashboard/zmq_dispatcher.py", line 254, in process_log
    jsonevent = json.loads(eventdata)
  File "/usr/lib/python3.5/json/__init__.py", line 319, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.5/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.5/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
````
How are you running the "start_all.sh" script as virtualenv when passed to crontab at reboot or rc.local?

**Comment by mokaddem** [comment]
Of course, you need to be in a virtualenv.
I usually start it manually but using rc.local should work.

**Comment by faustus25** [comment]
Can you specify how it runs in rc.local so I can test it (did you simply add the start_all script there)?

I notice that the start_all.sh script crashes (either zmq_subscriber or zmq_dispatcher with the error in my previous post) if the event has 1000+ attributes in it specifically if the event is from a Default or Custom Feed. Some of my Custom Feeds have 100,000+ attributes:
e.g. hosts-file.net - hphost - malwarebytes feed   165060 attributes

**Comment by mokaddem** [comment]
Exactly: ``bash /var/www/misp-dashboard/start_all.sh``
Adding that much attributes should not be a problem, it will be slow but it should eventually work.
Just a question, are you feeding the dashboard manually or are you simply letting MISP feed it through the standard ZMQ?

**Comment by faustus25** [comment]
MISP feed is automatically feeding to those events to the dashboard, it just doesn't handle the attribute heavy events well. W

Latest issue I have running the zmq scripts:

````
redis.exceptions.ResponseError: MISCONF Redis is configured to save RDB snapshots, but is currently not able to persist on disk. Commands that may modify the data set are disabled. Please check Redis logs for details about the error.
````

Have you encountered this before?

Seen this as a possible workaround, any recommendations?:

````
redis-cli
CONFIG SET dir /tmp/some/directory/other/than/var
CONFIG SET dbfilename temp.rdb
BGSAVE
````

**Comment by faustus25** [comment]
I have decided to reinstall the dashboard according to the new MISP install guide:

[https://misp.github.io/MISP/INSTALL.ubuntu1804/#misp-dashboard](url)

Reloading the apache service fails:

````
 Reloading LSB: Apache2 web server.
apache2[5786]:  * Reloading Apache httpd web server apache2
apache2[5786]:  *
apache2[5786]:  * The apache2 configtest failed. Not doing anything.
apache2[5786]: Output of config test was:
apache2[5786]: AH00543: apache2: bad user name misp
apache2[5786]: Action 'configtest' failed.

````

Output of misp-dashboard.conf for Apache2:

````
<VirtualHost *:8001>
    ServerAdmin admin@admin
    ServerName misp.local
    DocumentRoot /var/www/misp-dashboard

    WSGIDaemonProcess misp-dashboard
        user=misp group=misp
        python-home=/var/www/misp-dashboard/DASHENV
        processes=1
        threads=15
        maximum-requests=5000
        listen-backlog=100
        queue-timeout=45
        socket-timeout=60
        connect-timeout=15
        request-timeout=60
        inactivity-timeout=0
        deadlock-timeout=60
        graceful-timeout=15
        eviction-timeout=0
        shutdown-timeout=5
        send-buffer-size=0
        receive-buffer-size=0
        header-buffer-size=0
        response-buffer-size=0
        server-metrics=Off
    WSGIScriptAlias / /var/www/misp-dashboard/misp-dashboard.wsgi
    <Directory /var/www/misp-dashboard>
        WSGIProcessGroup misp-dashboard
        WSGIApplicationGroup %{GLOBAL}
        Require all granted
    </Directory>
    LogLevel info
    ErrorLog /var/log/apache2/misp-dashboard.local_error.log
    CustomLog /var/log/apache2/misp-dashboard.local_access.log combined
    ServerSignature Off
</VirtualHost>

````

**Comment by faustus25** [comment]
The error has not appeared since the redis-cli config change. Will close this for the moment and monitor for any reoccurence.

**Comment by faustus25** [comment]
Error reoccurred stopping zmq dispatcher and subscriber so disabled RDB snapshots

````
$ redis-cli
> config set stop-writes-on-bgsave-error no
````

This comes with a previso: "this is recommended only if you don't have RDB snapshots enabled or if you don't care about data persistence in the snapshots."

@mokaddem: Have you had a similar issue and remediated similarly?

**Comment by faustus25** [comment]
I will look into increasing the memory for the VM.

In terms of feeds for MISP (both default and custom) these are the top 5 which put a huge load on the Redis server and as I have as fixed events when the zmq_dispatcher has to run through all these attribute heavy fixed events the zmq scripts fail:

All Current Dominas OSINT Bambenek: 2+million attributes
blocklist.de : 460,000+ attributes
ci-badguys: 383,000+ attributes
antisource: 297,000+ attributes
Alienvault Rep: 209,000+ attributes

You must create a new event for each pull of these feeds or not have them enabled possibly?

Fixed events with a huge volume of attributes show as above may not be recommended for the dashboard, curious if others have the same experience.

**Comment by shaykster** [comment]
Have a similar error - anyone seen the issue below;

(DASHENV) misp@misp:~/misp-dashboard-master$ 
(DASHENV) misp@misp:~/misp-dashboard-master$ ./zmq_dispatcher.py 
Traceback (most recent call last):
  File "./zmq_dispatcher.py", line 299, in <module>
    main(args.sleeptime)
  File "./zmq_dispatcher.py", line 274, in main
    process_log(zmqName, content)
  File "./zmq_dispatcher.py", line 256, in process_log
    dico_action[topic](zmq_name, jsonevent)
  File "./zmq_dispatcher.py", line 208, in handler_attribute
    trendings_helper.addTrendingCateg(categName, timestamp)
  File "/home/misp/misp-dashboard-master/helpers/trendings_helper.py", line 50, in addTrendingCateg
    self.addGenericTrending(self.keyCateg, categName, timestamp)
  File "/home/misp/misp-dashboard-master/helpers/trendings_helper.py", line 43, in addGenericTrending
    self.serv_redis_db.zincrby(keyname, to_save, 1)
  File "/home/misp/misp-dashboard-master/DASHENV/lib/python3.6/site-packages/redis/client.py", line 2281, in zincrby
    return self.execute_command('ZINCRBY', name, amount, value)
  File "/home/misp/misp-dashboard-master/DASHENV/lib/python3.6/site-packages/redis/client.py", line 755, in execute_command
    return self.parse_response(connection, command_name, **options)
  File "/home/misp/misp-dashboard-master/DASHENV/lib/python3.6/site-packages/redis/client.py", line 768, in parse_response
    response = connection.read_response()
  File "/home/misp/misp-dashboard-master/DASHENV/lib/python3.6/site-packages/redis/connection.py", line 638, in read_response
    raise response
redis.exceptions.ResponseError: value is not a valid float
(DASHENV) misp@misp:~/misp-dashboard-master$ 
(DASHENV) misp@misp:~/misp-dashboard-master$
