### ISSUE TITLE
How to start Misp-dashboard on version 2.4.100

### ISSUE THREAD

**Issue by Nightmarekcatta** [MISP/misp-dashboard#78]
![image](https://user-images.githubusercontent.com/44956276/50756526-1ac12680-128f-11e9-8393-f7b282490d87.png)

**Comment by Nightmarekcatta** [comment]
When i tried to access on web browser
![image](https://user-images.githubusercontent.com/44956276/50758023-8efdc900-1293-11e9-8aba-fafcd64be56c.png)

**Comment by Nightmarekcatta** [comment]
Done! Try to deploy

**Comment by mokaddem** [comment]
Glad to see you managed to solve the issue by yourself!
I just saw that the GeoLite2 file is not uncompressed correctly in the latest MISP virtual machine.
I guess you fixed it manually.
