### ISSUE TITLE
Log absolute path is required if misp-dashboard path is different from default

### ISSUE THREAD

**Issue by francesco-ficarola** [MISP/misp-dashboard#80]
Hello,

please add to the README file a notice that informs an absolute path is required if MISP dashboard's path is different from default `/var/www/misp-dashboard`. Indeed, copying MISP dashboard into `/var/www/MISP/misp-dashboard`, if the config variable is set to `directory=logs`, then apache warns it has not the right permissions to write (likely it does not find the correct log file). Changing the variable like this `directory=/var/www/MISP/misp-dashboard/logs`, then it works.

Furthermore, please add a notice about `start_all.sh` since I found it pretty useful.

Thanks,
Francesco

**Comment by mokaddem** [comment]
Hello,
I added the notice about ``start_all.sh`` to the README. Thanks for the feedback!

Regarding the log directory, having a relative path (``directory=logs``) allows the dashboard to work out of the box for default installations (MISP VM and local setup).
Of course, if you drift from the default setup, you are free to edit the configuration file as much as you want.

**Comment by francesco-ficarola** [comment]
Thanks. Regarding the relative path of logs, please verify if it properly works using different paths for MISP Dashboard. I had some issues, for that reason I changed it into absolute path. Following the log:

    [Fri Feb 08 10:22:18.365494 2019] [wsgi:error] [pid 1137] [client 192.168.10.203:60392] mod_wsgi (pid=1137): Target WSGI script '/var/www/MISP/misp-dashboard/misp-dashboard.wsgi' cannot be loaded as Python module.
    [Fri Feb 08 10:22:18.365545 2019] [wsgi:error] [pid 1137] [client 192.168.10.203:60392] mod_wsgi (pid=1137): Exception occurred processing WSGI script '/var/www/MISP/misp-dashboard/misp-dashboard.wsgi'.
    [Fri Feb 08 10:22:18.366236 2019] [wsgi:error] [pid 1137] [client 192.168.10.203:60392] Traceback (most recent call last):
    [Fri Feb 08 10:22:18.366269 2019] [wsgi:error] [pid 1137] [client 192.168.10.203:60392]   File "/var/www/MISP/misp-dashboard/misp-dashboard.wsgi", line 4, in <module>
    [Fri Feb 08 10:22:18.366275 2019] [wsgi:error] [pid 1137] [client 192.168.10.203:60392]     from server import app as application
    [Fri Feb 08 10:22:18.366297 2019] [wsgi:error] [pid 1137] [client 192.168.10.203:60392]   File "/var/www/MISP/misp-dashboard/server.py", line 48, in <module>
    [Fri Feb 08 10:22:18.366301 2019] [wsgi:error] [pid 1137] [client 192.168.10.203:60392]     live_helper = live_helper.Live_helper(serv_redis_db, cfg)
    [Fri Feb 08 10:22:18.366306 2019] [wsgi:error] [pid 1137] [client 192.168.10.203:60392]   File "/var/www/MISP/misp-dashboard/helpers/live_helper.py", line 22, in __init__
    [Fri Feb 08 10:22:18.366309 2019] [wsgi:error] [pid 1137] [client 192.168.10.203:60392]     os.makedirs(logDir)
    [Fri Feb 08 10:22:18.366314 2019] [wsgi:error] [pid 1137] [client 192.168.10.203:60392]   File "/usr/lib/python3.6/os.py", line 220, in makedirs
    [Fri Feb 08 10:22:18.366317 2019] [wsgi:error] [pid 1137] [client 192.168.10.203:60392]     mkdir(name, mode)
    [Fri Feb 08 10:22:18.366334 2019] [wsgi:error] [pid 1137] [client 192.168.10.203:60392] PermissionError: [Errno 13] Permission denied: 'logs'
