### ISSUE TITLE
Date format fix

### ISSUE THREAD

**Issue by SteveClement** [MISP/misp-dashboard#99]
Depending on your configured timezone the date is displayed wrong, for me:

10:16:54 GMT+0900 (Japan 5/31/2019

**Comment by SteveClement** [comment]
"found" where the date is being set, the question is what the initial authors had in mind when showing time and date?

**Comment by bm11100** [comment]
@SteveClement, I have a similar issue https://github.com/MISP/MISP/issues/7765. Where is the time set for the footer? My system time is correct.
